### ISSUE TITLE
Add Direct URLs for Node1 and Node2

### ISSUE THREAD

**Issue by super3** [ovsoinc/yacdn.org#101]
https://node1.yacdn.org
https://node2.yacdn.org

**Comment by super3** [comment]
@montyanderson This works now, but I get SSL errors.

**Comment by super3** [comment]
@montyanderson Thoughts on this?

**Comment by montyanderson** [comment]
@super3 Been deep in nginx config all morning, got it working though on node1 :) will add to node2.

**Comment by super3** [comment]
Note that it works on https on node1 but not http.

**Comment by montyanderson** [comment]
@super3 working on both :)

**Comment by super3** [comment]
- [ ] http://node1.yacdn.org/ doesn't work
- [ ] http://node2.yacdn.org/ doesn't work
- [ ] http2://node2.yacdn.org/ returns a cert error

@montyanderson Doesn't work for me.

**Comment by montyanderson** [comment]
@super3 Apologies, I reverted the configs after testing.

Can you confirm all work now?

**Comment by super3** [comment]
@montyanderson Can confirm that it works perfectly now.
