### ISSUE TITLE
HTTP of YaCDN.org Returns 400 Error

### ISSUE THREAD

**Issue by super3** [ovsoinc/yacdn.org#117]
http://yacdn.org

**Comment by montyanderson** [comment]
@super3 I thought that the redirection code looked completely fine, so I tried http://node1.yacdn.org and http://node2.yacdn.org - both of which redirect properly.

This leads me to think this could be a problem of scaleway's load balancer only working on https ports (443) and not http port 80 as well.

**Comment by super3** [comment]
@montyanderson You are 100% correct. It was a reconfigured scaleway load balancer. The port 80 frontend was pointing to the SSL(443) backend.
