### ISSUE TITLE
Create Embedable Javascript Script 

### ISSUE THREAD

**Issue by super3** [ovsoinc/yacdn.org#125]

**Comment by montyanderson** [comment]
<img data-yacdn="url here">

**Comment by montyanderson** [comment]
Todo: Research other CDNs and what they do

**Comment by montyanderson** [comment]
Cloudflare functions as a passthrough for entire sites.

You use their DNS servers, which proxy all sites through their servers. I think we could build something similar in a full-on week, but the difficult part on top would be building UIs/interfaces.

**Comment by super3** [comment]
So perhaps we should just focus on larger static files rather than a DNS
proxy?

**Comment by montyanderson** [comment]
@super3 For certain. I think we should go bigger than images too.

**Comment by super3** [comment]
Video is the holy grail, although I would like to do binaries. Lets close this issue since we are not doing it.
