### ISSUE TITLE
yacdn.org https cert

### ISSUE THREAD

**Issue by MilzoCSP** [ovsoinc/yacdn.org#165]
Your https certificate has expired for that domain.

**Comment by LS-TV** [comment]
You website and service is unusable because of this issue.

I note that tt's a LetsEncrypt certificate which i thought are normally automatically renewed by the host... but not in the case of your website for some reason.

Please advise ETA.

**Comment by montyanderson** [comment]
It looks like there was a bug in an older version of LetsEncrypt that stopped auto-renew.

Will have this sorted out asap.

**Comment by super3** [comment]
@MilzoCSP @LS-TV Fixed. Sorry for the delay.
