### ISSUE TITLE
Hosted service returning 502

### ISSUE THREAD

**Issue by mitchellnemitz** [ovsoinc/yacdn.org#26]
I'm unsure of the expected reliability of the service, so forgive me if these sorts of blips are expected.

Example: https://yacdn.org/proxy/https://google.com

<img width="816" alt="screen shot 2019-01-24 at 6 19 57 pm" src="https://user-images.githubusercontent.com/1457482/51714912-ba5b1480-2004-11e9-84cc-cbba1b75fc3e.png">

**Comment by mitchellnemitz** [comment]
@super3 or @montyanderson, do you have any information on the hosted yacdn.org platform?

**Comment by super3** [comment]
Exceeded bandwidth usage, so I need to move servers. Got busy, but I can
try to do it today or tomorrow. Are you a previous or a new user?

**Comment by montyanderson** [comment]
Happy to look into this but I think it just requires @super3 to add more bandwidth.

I'll investigate throttling.

**Comment by super3** [comment]
We could put together a support/hosted plan if you would like. Are you
using the CDN or the proxy part? How much bandwidth do you expect to use?

**Comment by super3** [comment]
@mitchellnemitz Sorry it took longer than expected. The hosted service is back online.

**Comment by ickata** [comment]
Service is still down, at least on my end...

**Comment by montyanderson** [comment]
@ickata We're still in demo stages. Working on it.

**Comment by super3** [comment]
@ickata It should be back up today. We maxed out the old server.
