### ISSUE TITLE
Newer Docker Image

### ISSUE THREAD

**Issue by JohnTrabusca** [ovsoinc/yacdn.org#265]
Is there any newer docker image available for this project ? I was using the /serve endpoint for m3u8 files but since it's no longer working, I'd like to set this up on my own server, but using the .sh file and the docker image available right now does not work.

**Comment by JohnTrabusca** [comment]
@super3

**Comment by super3** [comment]
@JohnTrabusca Unfortunately not. We stopped maintaining this service, due to lack of time.
