### ISSUE TITLE
Spam Control

### ISSUE THREAD

**Issue by montyanderson** [ovsoinc/yacdn.org#34]
Blacklist.txt should block all requests coming with a Referer header from one of the domains.

**Comment by super3** [comment]
@montyanderson Since this is now on an unmetered server I'm not worried about abuse/spam usage until the traffic meets 100 Mbit/s.

**Comment by super3** [comment]
@montyanderson We have 500 Mbit/s limit now on the main server, and two additional servers with 100 Mbit/s each. When you have the header information added to logs, we can implement domain blacklisting when we hit some Mbit limit.

**Comment by super3** [comment]
@montyanderson 
![screenshot](https://user-images.githubusercontent.com/60975/53774168-6d981280-3ebb-11e9-8cb7-65993f8dd0bf.png)

Looks like we are not in excess of 500 Mbit/s. Can we have a blacklist.txt that we can add domains to?

**Comment by montyanderson** [comment]
@super3 Should this blacklist block all requests coming with a `Referer` header from one of the domains

**Comment by super3** [comment]
Yes, I think that makes the most sense.
