### ISSUE TITLE
Track Storage Usage

### ISSUE THREAD

**Issue by montyanderson** [ovsoinc/yacdn.org#40]
- [x] Config provides a maximum size for the file
- [x] Config provides a maximum allocated space for the service 
- [x] Server will delete oldest* files to keep space under maximum allocated space

*Oldest should be determined by time last accessed vs time, so a frequently requested file will stay in cache.

**Comment by super3** [comment]
Low priority since people are mostly using the proxy endpoint.

**Comment by super3** [comment]
@montyanderson Are we doing any of these now?

**Comment by montyanderson** [comment]
There are at least two race conditions involved here.

https://github.com/ovsoinc/yacdn.org#expiry

**Comment by montyanderson** [comment]
Conversation moved to #61

**Comment by montyanderson** [comment]
All completed, in production too.
