### ISSUE TITLE
Rewrite /serve to be as fast as proxy - possibly combine endpoints

### ISSUE THREAD

**Issue by montyanderson** [ovsoinc/yacdn.org#43]

**Comment by super3** [comment]
@montyanderson So right now the largest user of the service is only using the proxy for whatever reason. So if we combine the endpoints, we will be go from caching very little data to a ton (currently passing 12.6TB total). Right now there is a ton of requests for different segments of a video, but without having a method to look at them in total I have no idea if there is overlap. 

If there is overlap (segments are requested multiple times), then we will save a ton of bandwidth and there will be a maximum amount of space used. If there is not overlap then we have to be aware that server will be constantly add/deleting data and we have to implement #40 before we combine endpoints or we will just run out of space on the VPS.

**Comment by montyanderson** [comment]
@super3 Both `/serve` and `/proxy` work in the exact same way: `/proxy` is essentially `/serve` with a `maxAge` of 0. This means that running a `/proxy` also functions to update the latest version inside the cache. Everything is streamed and chunked, from the original server and simultaneously to the cache and the client.

Should we look at combining these endpoints?

**Comment by montyanderson** [comment]
I'm tempted to say make `/proxy` route directly to `/serve`, also with a default maxAge of 24 hours.

**Comment by super3** [comment]
Our traffic died down because I think we are in a different region than
what people expected. I'd make the /proxy route directly to /serve with a
maxAge of 24 hours so it will have the exact same function(and we have the
bandwidth).

My only hesitation is that under high traffic we don't have logic to manage
the disk space and we will hit the limit and crash the server.

**Comment by super3** [comment]
According to my math at peak load it only takes 10 minutes to fill the
cache.

**Comment by super3** [comment]
@montyanderson I think we should:
- [ ] allow the user to pass in a maxAge via GET argument
- [ ] not save the file in cache if the maxAge is 0
- [ ] update the documentation to include maxAge 
- [ ] deprecate the proxy endpoint

Thoughts?

**Comment by montyanderson** [comment]
@super3 the first one is already implemented!

I use it in the tests :)

**Comment by super3** [comment]
@montyanderson Great work. Let's close this issue out.
