### ISSUE TITLE
Process Logs and Put on Dashboard

### ISSUE THREAD

**Issue by super3** [ovsoinc/yacdn.org#49]

**Comment by montyanderson** [comment]
What dashboard is this?

**Comment by super3** [comment]
https://grafana.com/
https://www.elastic.co/webinars/getting-started-kibana

PM2 dashboard (PM2 Plus) doesn't seem ideal.

**Comment by montyanderson** [comment]
@super3 I'll have a look to see if there any node dashboards that we can push custom data too.

**Comment by montyanderson** [comment]
I can't seem to find anything.

**Comment by super3** [comment]
@montyanderson Here are the options in order of preference:

1) https://papertrailapp.com/
2) https://logz.io/
3) https://www.loggly.com/

**Comment by montyanderson** [comment]
@super3 Experimenting with a papertrail setup. Code coming soon :)

**Comment by super3** [comment]
Yay!

**Comment by super3** [comment]
@montyanderson Update?
