### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by lucacastagnotto** [ovsoinc/yacdn.org#60]
Yesterday i tried again a fetch call that always worked but i keep getting "Failed to load resource: the server responded with a status of 500 (Internal Server Error)". The same call with an other cors proxy server do the job. Do you know why?

**Comment by super3** [comment]
We made some updates, so might be a bug on our part. Could you let us know what URL you are trying to call, and will try to debug.

**Comment by montyanderson** [comment]
Seems to be working as far as I can tell.

**Comment by lucacastagnotto** [comment]
It's the Dbpedia API and the url is:
var url="http://vmdbpedia.informatik.uni-leipzig.de:8080/api/1.0.0/values?property=dbo%3Aabstract&format=JSON&pretty=NONE&limit=100&offset=0&oldVersion=false&key=1234&oldVersion=false&entities=Michael_Schumacher"
My personal key is different but i can see it works also with key=1234. The call works either if i don't use cors proxy either if i use "https://cors-anywhere.herokuapp.com/" as proxy server.

**Comment by montyanderson** [comment]
@lucacastagnotto Koa is trimming query strings. Pushing a fix now :)

**Comment by montyanderson** [comment]
@lucacastagnotto Fixed :)

https://yacdn.org/proxy/http://vmdbpedia.informatik.uni-leipzig.de:8080/api/1.0.0/values?property=dbo%3Aabstract&format=JSON&pretty=NONE&limit=100&offset=0&oldVersion=false&key=1234&oldVersion=false&entities=Michael_Schumacher

**Comment by lucacastagnotto** [comment]
Unfortunately making the call from Javascript it still doesn't work but there is no more Internal Server Error. Now i get the more usual: "Access to fetch at 'https://yacdn.org/proxy/http://vmdbpedia.informatik.uni-leipzig.de:8080/api/1.0.0/values?property=dbo%3Aabstract&format=JSON&pretty=NONE&limit=100&offset=0&oldVersion=false&key=1234&oldVersion=false&entities=Michael_Schumacher' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."
Am i missing something? It worked until last week.

**Comment by montyanderson** [comment]
@lucacastagnotto Moved to #62
