### ISSUE TITLE
LRU Cache

### ISSUE THREAD

**Issue by montyanderson** [ovsoinc/yacdn.org#61]
I'm creating a code flow that should be immune to race conditions. Requires that we maintain a last-accessed sorted set.

* get redis `cache-storage-usage` and increment by new file size
* calculate amount of space needed to make space for new file
* **atomically** (through single redis splices) delete files in the cache up to that amount of space
* download into cache

**Comment by montyanderson** [comment]
The only race condition I can think of is this:

* request a requests a file, exists in redis
* request b deletes the entry in redis and the file in the filesystem
* request a/b errors as file is being deleted while being read

**Comment by super3** [comment]
@montyanderson This is a very rare edge case, but since the cache size is only 50 GB we could encounter it. Go ahead and implement.

**Comment by montyanderson** [comment]
@super3 This is currently working in test conditions.
