### ISSUE TITLE
Add Standard Labels

### ISSUE THREAD

**Issue by super3** [ovsoinc/yacdn.org#65]
#### Resources
- https://github.com/popomore/github-labels
- https://gist.github.com/super3/0596e3c7c8bb173815cae03a38f832b8
- https://developer.github.com/v3/issues/labels/

**Comment by montyanderson** [comment]
@super3 The github-labels module wouldn't authenticate for me so I made our own script that does the same thing more simply.

https://github.com/ovsoinc/push-labels
