### ISSUE TITLE
Distributed registry

### ISSUE THREAD

**Issue by montyanderson** [ovsoinc/yacdn.org#87]
Implement a 'best gateways for me' endpoint for all servers, returning 5 or n.

**Comment by montyanderson** [comment]
@super3 I've implemented a `/nodes` endpoint.

https://yacdn.org/nodes?longitude=51.5074&latitude=0.1278

```
[{"url":"https://yacdn.org","distance":"7164.6227"}]
```

**Comment by super3** [comment]
@montyanderson So this returns a distance of the server relative to the longitude and latitude that you passed in via the GET query params? 

To make this easier to use perhaps we should do a geo-ip lookup from the requester? Don't really expect users to lookup their long and lat.

**Comment by montyanderson** [comment]
@super3 for sure. i think we should try and do this completely locally to reduce latency, rather than calling an external service.

**Comment by super3** [comment]
Here you go: [https://dev.maxmind.com/geoip/geoip2/downloadable/](https://dev.maxmind.com/geoip/geoip2/downloadable/). I'd prefer we use an external service right now. MVP vs v2.

**Comment by montyanderson** [comment]
Alpha version of IP geolocation working on dev branch - further testing needed
