### ISSUE TITLE
Fails on HTTP 1.0 responses, no content-type header

### ISSUE THREAD

**Issue by montyanderson** [ovsoinc/yacdn.org#88]

**Comment by super3** [comment]
@montyanderson Does this bug still exist?

**Comment by montyanderson** [comment]
@super3 Yes - and I'm not completely sure how to mitigate it.

**Comment by super3** [comment]
We will just leave it in the issue queue for now then.

**Comment by montyanderson** [comment]
Todo: add explicit error handling to this

**Comment by super3** [comment]
@montyanderson You added this, just not the tests right?
